export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS';
export const GET_TRENDING_MOVIE = 'GET_TRENDING_MOVIE';
export const GET_MOVIE_TOP = 'GET_MOVIE_TOP';
export const GET_MOVIE_ACTION = 'GET_MOVIE_ACTION';
export const GET_MOVIE_COMEDY = 'GET_MOVIE_COMEDY';

export const GET_MOVIE_HORNOR = 'GET_MOVIE_HORNOR';
export const GET_MOVIE_ROMANCE = 'GET_MOVIE_ROMANCE';
export const GET_MOVIE_DOCUMENT = 'GET_MOVIE_DOCUMENT';



